### ISSUE TITLE
Thank you 🎉

### ISSUE THREAD

**Issue by Splines** [QBobWatson/ila#16]
Hey, don't know if this is the right place but I just wanted to thank all the people involved in this amazing book, it's truly a pleasure to read. The concepts become so clear with all these amazing graphics, tikz pictures and even MathBox interactivity. So much work must have gone into it from conceptualization to graphics, nice explanations and customaization of PreTeXt. Thank you for all your effors, it really pays off for the readers and I wish more books like this one were out there.

**Comment by QBobWatson** [comment]
Thanks for the kind words!  I'm actually in the process of rewriting the book from start to finish -- my current progress is in the "duke" branch.  The Duke version will cover the SVD, among other things, so keep an eye out for that :)
